version: '3'
services:
  redis:
    image: "redis:alpine"
    ports:
      - 6379:6379
  db:
    image: mdillon/postgis
    restart: on-failure
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: project
      POSTGRES_DB: project-api
      POSTGRES_PASSWORD: root
